In [2]:
import torch

In [13]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])
x*y

tensor([10.,  3.])

In [14]:
x = torch.zeros([2,5])
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [17]:
y = torch.rand(2,5)

In [18]:
y

tensor([[0.0967, 0.2002, 0.7721, 0.4100, 0.8618],
        [0.9214, 0.9783, 0.4658, 0.8548, 0.3575]])

In [19]:
y.view([1,10])

tensor([[0.0967, 0.2002, 0.7721, 0.4100, 0.8618, 0.9214, 0.9783, 0.4658, 0.8548,
         0.3575]])