In [13]:
import torch

In [14]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])
x*y

tensor([10.,  3.])

In [15]:
x = torch.zeros([2,5])
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [16]:
y = torch.rand(2,5)

In [17]:
y

tensor([[0.2405, 0.7770, 0.3820, 0.7842, 0.6154],
        [0.1673, 0.3365, 0.8131, 0.5446, 0.6336]])

In [18]:
y.view([1,10])

tensor([[0.2405, 0.7770, 0.3820, 0.7842, 0.6154, 0.1673, 0.3365, 0.8131, 0.5446,
         0.6336]])